package com.example.cvmaker.model.profilemodels.profile

data class sdasdasdasItem(
    val achievements_and_awards: List<Any>,
    val activities: List<Any>,
    val additional_info: String,
    val address: String,
    val cover_letter: String,
    val cv_email: String,
    val date_of_birth: Any,
    val default: Boolean,
    val designation: String,
    val driving_license: String,
    val educations: List<Any>,
    val experiences: List<Any>,
    val first_name: String,
    val gender: String,
    val id: Int,
    val image: String,
    val industry_knowledge: List<Any>,
    val interests: List<Any>,
    val languages: List<Any>,
    val last_name: String,
    val marital_status: String,
    val objective: String,
    val other_skills: List<Any>,
    val phone: String,
    val projects: List<Any>,
    val publications: List<Any>,
    val references: List<Any>,
    val social: SocialX,
    val status: Boolean,
    val tools: List<Any>,
    val user: Int,
    val website: String
)